### ISSUE TITLE
ImportError: libhdf5_serial.so.103

### ISSUE THREAD

**Issue by chongkkmy** [praveens-git/Face-Recognition-Attendance-System#1]
Good Day Sir, I'm trying around with your code and there are few errors preventing to run. 

Under line 18,19,20 " \ " is prevent the code to run.
image_source = 'Images\ '
user_path = 'Data\user_list.txt'
reference = "Data\reference.yml" 
<img width="556" alt="Screenshot 2020-10-25 at 4 47 51 AM" src="https://user-images.githubusercontent.com/1709993/97093382-0164b680-167e-11eb-9362-8bc73815bf24.png">

There is also another error mention that ImportError: libhdf5_serial.so.103: cannot open shared object file: No such file or directory
<img width="561" alt="Screenshot 2020-10-25 at 4 47 34 AM" src="https://user-images.githubusercontent.com/1709993/97093401-2bb67400-167e-11eb-875e-24dcd7674511.png">

Anyidea how to fix these? Many Thanks

**Comment by praveens-git** [comment]
To solve the first error just edit the main.py file and change '\\' to '/'. Sorry it is due to the fact that finally tested on windows. It will clear the first issue.

Change all '\\'.

**Comment by praveens-git** [comment]
In second there is a typo.
`from cv2 import *`

correct this.

I will change these on my repo.

**Comment by praveens-git** [comment]
Do you have opencv library installed?

If not try pip3 install opencv-python. or try compiling yourself.(refer official docs.)

**Comment by chongkkmy** [comment]
Thanks for your reply, I manage to get all the sorted. The installation of your requirement.txt is not enough, I followed another tutorial to get a full installation of OpenCV for raspberry pi.

However, I got into another error while I'm trying to enrol new user. The camera did took a photo of me and save into /images folder. could you please advice? Thanks
<img width="568" alt="Screenshot 2020-10-25 at 6 55 29 PM" src="https://user-images.githubusercontent.com/1709993/97105258-7a9ef080-16f4-11eb-9221-31af088fec4f.png">

**Comment by praveens-git** [comment]
Ok. It seems the gray variable or classifier is empty. Can you check that. In that How many photos do you see. A proper set should contain 10 photos.

**Comment by chongkkmy** [comment]
oops, I forgot to include the data/haarcascades/haarcascade_frontalface_default.xml from OpenCV to the main folder. Now it is working inside the image folder there is now 2 images. Sample.jpg(the actual photo from camera) and 1.jpg(greyscale cropped photo). Now I got massage saying the "cannot connect to X server"
<img width="601" alt="Screenshot 2020-10-25 at 7 22 02 PM" src="https://user-images.githubusercontent.com/1709993/97105635-61e40a00-16f7-11eb-9bd8-cff9782a781e.png">

I had double check with my mysql login information, it is correct. if I enter with the wrong login details, there will be an error before main.py could run.

**Comment by praveens-git** [comment]
Sorry for all the above problems. I am new to github and had some troubles. Anyway thanks for checking out my code.
